### ISSUE TITLE
common.notification.error

### ISSUE THREAD

**Issue by battosai30** [flowforge/node-red-function-gpt#16]
### Current Behavior

I've just installed this node on my own NodeRed instance, not FlowForge (maybe it's the problem ?)

API key + OrgID configured (Keys used in other services so sure they're valid)
Model = code-davinci-002 or gpt-3.5-turbo

Click on "Ask ChatGPT" immediatly leads to a popup "common.notification.error"

![image](https://user-images.githubusercontent.com/5184702/236140101-8a4faa7a-4556-48b3-b41d-47f0a13f18f3.png)

### Environment

- NodeRed version: 3.0.1
- Platform/OS: Linux Debian10
- Browser: Firefox

**Comment by joepavitt** [comment]
Thanks for raising the issue. It should definitelt work outside of FlowForge, we didn't want to gate keep!

Could I check, upon adding the node to the canvas, did you deploy first, before asking ChatGPT a question?

We have an issue at the moment where you need to deploy, once the node is added, but before tou written any code in the function node - see #13 

I would expect it to show a much nicer error than this though!

**Comment by oywino** [comment]
I'm not using FlowForge, and I have the same issue.

**Comment by joepavitt** [comment]
Thanks for letting us know @oywino - are you using same Operating System and Browser combo as reported too?

Have you tried the steps I'd mentioned above?

**Comment by oywino** [comment]
> Thanks for letting us know @oywino - are you using same Operating System and Browser combo as reported too?
> 
> Have you tried the steps I'd mentioned above?

NodeRed: 3.0.2
Docker container
Chrome on Win 10

I have tried all the steps recommended.

Rgds
Oywin

**Comment by joepavitt** [comment]
@Steve-Mcl can you think of anything we added that would have been Node-RED 3.1 specific? I know we used 3.1 when dev'ing. I can't think of anything obvious myself?

Will try this out for myself once I'm back at my desk on Tuesday.

Thanks both for the details.

**Comment by Steve-Mcl** [comment]
No, can't think of anything specific to either FlowForge or 3.1-beta.

**Comment by oywino** [comment]
What does the error message common.notification.error actually mean in this context? 

Rgds
Oywin

**Comment by joepavitt** [comment]
It means that Steve and I forgot to put a proper error message in and that Node-RED is resorting to a default placeholder 😬

**Comment by joepavitt** [comment]
Do tou see any errors reported in the Node-RED terminal/code line logs?

**Comment by oywino** [comment]
I'm not sure where to find that/those logs. Please direct me.

**Comment by joepavitt** [comment]
When you run Node-RED from the command line, or within the Docker container, you should see the logs printed there as it starts up.  Wherever you run the `node-red` command from.

**Comment by battosai30** [comment]
- In my case it's a "native" install, no Docker. 
- It's a Debian strech in LXC container (Proxmox OS). I upgraded it to Buster => same result
- Default log level doesn't show anything. Debug level show this : 
`[warn] [function-gpt] Registered invalid property name 'functionExternalModules'. Properties for this node must start with 'functionGpt'`

- Deploy first doesn't change anything.
- I observed that the notification pop up is very quick to show up, like it does not reach the step where HTTP request to Openai is done. Maybe a clue ?

**Comment by joepavitt** [comment]
Thanks @manglemender - just to check you mentioned you `tested the chrome browser and works OK` but the original browser you mentioned that you used was `Chrome on Win10` - what changed?

**Comment by joepavitt** [comment]
<img width="448" alt="Screenshot 2023-05-09 at 17 06 05" src="https://github.com/flowforge/node-red-function-gpt/assets/99246719/032d8b43-3f9c-4dc5-beda-1c45728fc8b7">

So the error is being triggered by the `RED.auth.needsPermission` middleware, which is returning a 401. @Steve-Mcl we set it as:

```js
RED.auth.needsPermission("function-gpt.write")
```

which on review back, doesn't look right, where would this value be set?

This is venturing outside of my own Node-RED dev knowledge

**Comment by Steve-Mcl** [comment]
Fyi, I have resolved this locally and will publish an update tomorrow.

**Comment by oywino** [comment]
Great! 
Can't wait to hear about it 🤗

**Comment by oywino** [comment]
> Fyi, I have resolved this locally and will publish an update tomorrow.

Nothing came.....   😪

**Comment by Steve-Mcl** [comment]
> > Fyi, I have resolved this locally and will publish an update tomorrow.
> 
> Nothing came..... 😪

I've had a busy day :) 

however, if you look again...

**Comment by oywino** [comment]
> I've had a busy day :)
> however, if you look again...

Look where?

**Comment by joepavitt** [comment]
@oywino Steve has opened a PR. I'll review today hopefully and if all is working, have it released later

**Comment by joepavitt** [comment]
We have just published v0.2.1 to the Node-RED library with a fix in for this, in addition to more verbose error logging. This may take half an hour or so to refresh in the "Palette" of Node-RED.

**Comment by battosai30** [comment]
Upgraded aaaannnnnnddddddd ...... it works :) 

Thank you !
